guru3/urls.py
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path, include, reverse_lazy, register_converter
from django.views.generic import RedirectView
from django.views.static import serve
from core.forms.auth import RegistrationFormUniqueEmailWithProfile, GuruAuthenticationForm
from core.converters import LegacyHostingConverter, legacyPath
from core.views.common import SupportView
from core.views.registration import RegistrationViewWithRequest

register_converter(LegacyHostingConverter, 'ext')

@login_required
def protected_serve(request, path, document_root=None, show_indexes=False):
    return serve(request, path, document_root, show_indexes)

urlpatterns = [
     path('', RedirectView.as_view(
        url = reverse_lazy("event.phonebook", kwargs={'ext':'php'}),
     )),
     path('api/', include('core.urls.api')),
     path('admin/', include('core.urls.admin')),
     legacyPath('event.<ext:ext>/', include('core.urls.events')),
     path('event/', include('core.urls.events')),
     legacyPath('extension.<ext:ext>/', include('core.urls.extension')),
     path('extension/', include('core.urls.extension')),
     legacyPath('handset.<ext:ext>/', include('core.urls.handset')),
     path('handset/', include('core.urls.handset')),
     path('callgroup/', include('core.urls.callgroup')),
     legacyPath('callgroup.<ext:ext>/', include('core.urls.callgroup')),
     path('grandstream/', include('grandstream.urls')),
     path('snom/', include('snom.urls')),
     path('epddi/', include('epddi.urls')),
     path('inventory/', include('core.urls.inventory')),
     legacyPath('register.<ext:ext>', RegistrationViewWithRequest.as_view(
        form_class = RegistrationFormUniqueEmailWithProfile,
    ),
         name = "user.register"),
     path('register', RegistrationViewWithRequest.as_view(
        form_class = RegistrationFormUniqueEmailWithProfile,
    ),
         name = "user.register"),
    legacyPath('accounts.<ext:ext>/', include('django.contrib.auth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    legacyPath('accounts.<ext:ext>/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('django_registration.backends.activation.urls')),
    legacyPath('accounts/login.<ext:ext>', auth_views.LoginView.as_view(),
          {'template_name': 'registration/login.html',
           'authentication_form': GuruAuthenticationForm},
          name = 'login'),
    path('accounts/login', auth_views.LoginView.as_view(),
          {'template_name': 'registration/login.html',
           'authentication_form': GuruAuthenticationForm},
          name = 'login'),
    legacyPath('user.<ext:ext>/', include('core.urls.user')),
    path('user/', include('core.urls.user')),
    path('captcha/', include('captcha.urls')),
    path("support/",
         SupportView.as_view(
             template_name="support.html",
         ),
         name="support"),
    legacyPath('audio.<ext:ext>/', include('core.urls.audio')),
    path('audio/', include('core.urls.audio')),
    re_path(r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], protected_serve, {'document_root': settings.MEDIA_ROOT}),
]

if not settings.DEBUG:
    from django.conf.urls import handler404
    from django.shortcuts import render
    handler404 = lambda req, exception: render(req, "404.html", {}, status=404)

snom/urls.py
from django.urls import re_path, path
from django.shortcuts import get_object_or_404

from gcontrib.decorators import user_is_staff
from gcontrib.views.meta import FlexibleTemplateView
from snom.views import provisioning
from snom.models import SnomFirmware

urlpatterns = [
    re_path(r"^prov/(?P<mac>[a-fA-Z0-9]{12})",
            provisioning,
            name="snom.provisioning"),
    re_path(r"^provdebug/(?P<mac>[a-fA-Z0-9]{12})",
            user_is_staff(provisioning),
            kwargs={"admin": True},
            name="snom.provisioning.debug"),
    path("firmware/<str:model>.xml",
         FlexibleTemplateView.as_view(
             template_params={
                 "firmware": lambda _r, kwargs: get_object_or_404(SnomFirmware, model=kwargs["model"]),
             },
             template_name="snom/firmware.xml",
         ),
        name="snom.provisioning.firmware"
    )

]

core/forms/audio.py
import hashlib

import magic
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from dal import autocomplete
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _

from core.models import AudioFile


class AudioFileForm(ModelForm):
    class Meta:
        model = AudioFile
        fields = [
            "name",
            "file",
        ]
        widgets = {
            "owner": autocomplete.ModelSelect2(url="user.autocomplete"),
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user")
        super(AudioFileForm, self).__init__(*args, **kwargs)

    def get_form_helper(self):
        helper = FormHelper()
        helper.add_input(Submit("save", _("Add Audio File")))
        return helper

    def clean_file(self):
        file_count = AudioFile.objects.filter(owner=self.user).count()
        if file_count >= 50 and not self.user.is_staff:
            raise ValidationError(_('User quota exceeded. Delete files first. 50 files maximum.'), code='maxfiles')
        file = self.cleaned_data.get('file', False)
        if file.size > (5*1024*1024):
            raise ValidationError(_('Audio File is to large (>5MB)'), code='toolarge')
        buf = file.read()
        mime = magic.from_buffer(buf, mime=True)
        if mime not in ['audio/mpeg', 'audio/x-wav']:
            raise ValidationError(_('File format [%s] is wrong. Only MP3 and WAV is supported.' % mime),
                                  code='wrongformat')
        hash_object = hashlib.sha512(buf)
        self.instance.sha512 = hash_object.hexdigest()
        return file

core/forms/handset.py
from django.forms import ModelForm

from core.models import DECTHandset


class HandsetEditForm(ModelForm):
    class Meta:
        model = DECTHandset
        fields = [
            "description",
            "vendor",
            "model_designation",
            "ipei",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["ipei"].disabled = True

core/forms/inventory.py
import datetime
import re

from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Field, Row, Column, Div, Layout, HTML, Submit

from core.models import InventoryItem, InventoryLend, Extension, Event
from core.utils import mac_format, ipei_normalize

from gcontrib.crispy_forms import defaultLayout


MAC_RE = re.compile("^(?:[0-9A-F]{2}(:|-)?){6}$", re.IGNORECASE)
IPEI_RE = re.compile("^\\d{5} ?\\d{7} ?[0-9*]$", re.IGNORECASE)


class InventoryItemForm(ModelForm):
    class Meta:
        model = InventoryItem
        fields = [
            "containedIn",
            "event",
            "itemType",
            "description",
            "serialNumber",
            "mac",
            "barcode",
            "comments",
            "decommissioned",
        ]

    def clean_mac(self):
        mac = self.cleaned_data.get("mac", "")
        if MAC_RE.match(mac):
            return mac_format(mac)
        elif IPEI_RE.match(mac):
            return ipei_normalize(mac)
        elif mac == "":
            return ""
        else:
            self.add_error("mac",
                           ValidationError(_("The mac needs to be either a valid Ethernet mac or a valid IPEI"),
                           code="mac-invalid"))
            return mac


class InventoryLendForm(ModelForm):
    class Meta:
        model = InventoryLend

        fields = [
            "lender",
            "comment",
        ]
    extension = forms.CharField(label=_("Extension"), required=False)

    def __init__(self, *args, **kwargs):
        self.event = kwargs.pop("event")
        self.inventory_item = kwargs.pop("inventory_item")
        super().__init__(*args, **kwargs)

    def clean_extension(self):
        extension = self.cleaned_data.get("extension")
        if extension is None or extension == "":
            return None

        try:
            return Extension.objects.get(event=self.event, extension=extension)
        except Extension.DoesNotExist:
            self.add_error("extension",
                           ValidationError(_("Extension unknown in current event."),
                                           code="extension-unknown"))

    def clean(self):
        _ = super().clean()
        if not self.inventory_item.isCurrentlyOnStock():
            self.add_error(None, "This item is already lent out. It needs to be returned first.")


class InventoryReturnForm(ModelForm):
    class Meta:
        model = InventoryLend

        fields = [
            "comment"
        ]

    box_barcode = forms.CharField(label=_("Box Barcode"), required=False,
                                  help_text=_("Scan a box this item is being put into. Leave empty to not pack into a box."))

    @property
    def form_helper(self):
        helper = FormHelper()
        helper.layout = Layout(
            Row(Column(Field("box_barcode"), css_class="col-md-6"),
                Column(
                    Div(
                        HTML("<div style=\"margin-bottom: 0.5rem\"><br /></div>"),
                        Div(HTML("(Scan box)"), css_id="box_description"),
                        css_class="col-md-6")
                ),
                ),
            Field("comment"),
        )
        helper.add_input(Submit("submit", "Return item into stock"))
        return helper


QUICK_ACCESS_MODE_CHOICES = (
    ("VIEW", "View item"),
    ("LR", "Lend/Return item"),
)


class InventoryQuickAccessForm(forms.Form):
    mode = forms.ChoiceField(label=_("Quick access mode"), choices=QUICK_ACCESS_MODE_CHOICES)
    barcode = forms.CharField(label=_("Barcode"), widget=forms.TextInput(attrs={"autofocus": "autofocus"}))

    def get_form_helper(self):
        helper = defaultLayout(self, "Go")
        helper.form_class = "form-inline"
        helper.label_class = 'col'
        helper.field_class = 'col'
        return helper

    def clean_barcode(self):
        barcode = self.cleaned_data.get("barcode", "")
        try:
            item = InventoryItem.find_item(barcode)
            return item
        except InventoryItem.DoesNotExist:
            self.add_error("barcode",
                           ValidationError("Unknown item", code="unkown-item"))


class InventoryPackBoxFom(forms.Form):
    box_barcode = forms.CharField(label=_("Box barcode"), widget=forms.TextInput(attrs={"autofocus": "autofocus"}))
    content_barcodes = forms.CharField(label=_("Content barcodes"), widget=forms.Textarea(attrs={"rows": "10"}))
    return_on_pack = forms.BooleanField(label=_("Return all items if currently lent out"), required=False, initial=True)
    repack_box = forms.BooleanField(label=_("Completely repack this box"), required=False, initial=False,
                                    help_text=_("Check this box to repack the box by completely defining its content instead of adding items."))

    @property
    def form_helper(self):
        helper = FormHelper()
        helper.layout = Layout(
            Row(Column(Field("box_barcode"), css_class="col-md-6"),
                Column(
                    Div(
                        HTML("<div style=\"margin-bottom: 0.5rem\"><br /></div>"),
                        Div(HTML("(Scan box)"), css_id="box_description"),
                        css_class="col-md-6")
                ),
            ),
            Row(Column(Field("content_barcodes"), css_class="col-md-6"),
                Column(
                    Div(
                        HTML("<div style=\"margin-bottom: 0.5rem\"><span id=\"content_count\">0</span> items<br /></div>"),
                        Div(HTML("(Scan content)"),  css_id="box_content_description"),
                    css_class="col-md-6")
                ),
            ),
            Field("return_on_pack"),
            Field("repack_box"),
        )
        helper.add_input(Submit("pack", "Pack box"))
        return helper

    def clean_content_barcodes(self):
        barcodes = self.cleaned_data["content_barcodes"]
        unique_barcodes = set([barcode.strip() for barcode in barcodes.split("\n")])
        items = InventoryItem.objects.filter(barcode__in=unique_barcodes)
        if len(unique_barcodes) != len(items):
            raise ValidationError("The item list contains invalid barcodes? See information on the right.")
        return items

    def clean_box_barcode(self):
        try:
            box = InventoryItem.objects.get(barcode=self.cleaned_data["box_barcode"])
        except InventoryItem.DoesNotExist:
            raise ValidationError("Invalid barcode.")
        if not box.itemType.isContainer:
            raise ValidationError("This item is no container? Wrong scan?")
        return box


class InventoryBoxEventAssignmentForm(forms.Form):
    event = forms.ModelChoiceField(Event.objects.all(), label=_("To which event should this box be assigned?"),
                                   empty_label="(Storage)", required=False,
                                   help_text="Select (Storage) to indicate that the items are now in storage and not assigned to the event anymore")
    barcodes = forms.CharField(label=_("Content barcodes"), widget=forms.Textarea(attrs={"rows": "10"}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["event"].queryset = Event.objects.filter(end__gte=datetime.date.today())


    @property
    def form_helper(self):
        helper = FormHelper()
        helper.layout = Layout(
            Field("event"),
            Row(Column(Field("barcodes"), css_class="col-md-6"),
                Column(
                    Div(
                        HTML("<div style=\"margin-bottom: 0.5rem\"><br /></div>"),
                        Div(HTML("(Scan content)"), css_id="barcodes_description"),
                        css_class="col-md-6")
                ),
                ),
        )
        helper.add_input(Submit("assign", "Assign boxes to event"))
        return helper

    def clean_barcodes(self):
        barcodes = self.cleaned_data["barcodes"]
        unique_barcodes = set([barcode.strip() for barcode in barcodes.split("\n")])
        items = InventoryItem.objects.filter(barcode__in=unique_barcodes)
        if len(unique_barcodes) != len(items):
            raise ValidationError("The item list contains invalid barcodes? See information on the right.")
        return items

core/forms/user.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _


class AdminUserEditForm(ModelForm):
    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "is_active",
            "is_staff",
        ]


class UserProfileForm(ModelForm):
    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "email",
        ]

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if self.instance is not None and self.instance.email == email:
            return email
        if User.objects.filter(email__iexact=email).count() > 0:
            self.add_error("email",
                           ValidationError(_("This email is already used by another account."),
                                           code="email-invalid"))


        return email

core/views/audio.py
import os

from django.conf import settings
from django.http import FileResponse, HttpResponse, Http404

from core.models import AudioFile
from core.tasks import process_ringback_file

from gcontrib.views.edit import OwnerSettingCrispyCreateView


class CreateRingbackView(OwnerSettingCrispyCreateView):
    def form_valid(self, form):
        result = super().form_valid(form)
        process_ringback_file.delay(form.instance.pk)
        return result


def download_audio(source_dir, request, hash):
    # Just check if this exists in principle
    if not AudioFile.objects.filter(sha512=hash).exists():
        raise Http404()

    outfile = os.path.join(source_dir, hash) + ".slin"
    # check if conversion ready
    if not os.path.isfile(outfile):
        return HttpResponse(b"Converted audio not available yet.", status=425)

    return FileResponse(open(outfile, "rb"))

core/views/registration.py
from django_registration.backends.activation.views import RegistrationView


class RegistrationViewWithRequest(RegistrationView):
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs

core/templates/inventory/item/delete.html
{% extends "master.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
<div class="col-md-6" style="margin: 0 auto;">
        <h2>Delete event</h2>
        <form method="POST">
            {% csrf_token %}
            Do you really want to remove the inventory item {{object.description}}?
            <p class="text-warning">
            <strong>WARNING:</strong>
                This functionality is only for wrongly created items. If we give things away, please just mark
                them as decommissioned.
            </p>
            {{form.as_p}}
            <div class="form-actions">
                <button type="Submit" class="btn btn-danger">Delete</button>
                <a href="{% url "inventory.item.list" %}" class="btn">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

core/templates/inventory/item/event_available.html
{% extends "master.html" %}
{% load crispy_forms_tags %}

{% block content %}
{% include "inventory/item/inventory-nav.html" with view="event_available" %}

<h1>Event inventory overview</h1>

<table class="table mt-4">
    <thead>
        <tr>
          <th scope="col">Item type</th>
          <th scope="col">Event total</th>
          <th scope="col">Event available</th>
        </tr>
  </thead>
  <tbody>
        {% for item_type in item_types %}
        <tr>
            <td>{{ item_type.itemType__name }}</td>
            <td>{{ item_type.event_total }}</td>
            <td>{{ item_type.event_available }}</td>
        </tr>
        {% endfor %}
  </tbody>
</table>

{% endblock %}

core/templates/inventory/item/inventory-nav.html
<ul class="nav nav-pills">
  <li class="nav-item">
    <a class="nav-link{% if view == "event_inventory" %} active{% endif %}" href="{% url "inventory.item.event_list" %}">Inventory (event)</a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% if view == "inventory" %} active{% endif %}" href="{% url "inventory.item.list" %}">Inventory (all)</a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% if view == "event_available" %} active{% endif %}" href="{% url "inventory.item.event_available" %}">Available (current event)</a>
  </li>
  <li class="nav-item">
      <a class="nav-link{% if view == "lent" %} active{% endif %}" href="{% url "inventory.item.lent" %}">Lent (current event)</a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% if view == "recall" %} active{% endif %}" href="{% url "inventory.recall_status" %}">Recall status</a>
  </li>
  {% if request.user.is_staff %}
  <li class="nav-item">
    <a class="nav-link{% if view == "lent+all" %} active{% endif %}" href="{% url "inventory.item.lent.all" %}">Lent (all events)</a>
  </li>
  {% endif %}
</ul>

core/templates/inventory/item/lend.html
{% extends "master.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h2>Lend inventory item</h2>

{% if form.errors %}
<div class="alert alert-danger" role="alert">
    Please correct your inputs!
</div>
{% endif %}

{% crispy form form_helper %}

{% endblock %}

core/templates/inventory/item/lend_edit.html
{% extends "master.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h2>Edit rental state</h2>

{% if form.errors %}
<div class="alert alert-danger" role="alert">
    Please correct your inputs!
</div>
{% endif %}

{% crispy form form_helper %}

{% endblock %}

core/templates/inventory/item/lentlist+all.html
{% include "inventory/item/lentlist.html" with view="lent+all" %}

core/templates/inventory/item/lentlist.html
{% extends "master.html" %}

{% block content %}
{% if view == "lent+all" %}
{% include "inventory/item/inventory-nav.html" with view="lent+all" %}
{% else %}
{% include "inventory/item/inventory-nav.html" with view="lent" %}
{% endif %}

<h1>Lent items</h1>

{% if view != "lent+all" %}
<ul class="nav justify-content-end mb-2">
  <li class="nav-item">
    <a class="nav-link" href="{% url "inventory.item.lent.csv" %}"><span class="oi oi-data-transfer-download"></span> Download inventory CSV</a>
  </li>
</ul>
{% endif %}


<div>
{% include "search-form.html" with placeholder="Descriptions, serial numbers, MACs, Extension, Lender ..." %}
</div>
<table class="table table-striped">
  <thead><tr>
    {% include "table-sort-header.html" with description="Type" key="type" %}
    {% include "table-sort-header.html" with description="Description" key="description" %}
    {% include "table-sort-header.html" with description="Barcode" key="barcode" %}
    {% include "table-sort-header.html" with description="Extension" key="extension" %}
    {% include "table-sort-header.html" with description="Name" key="name" %}
    {% include "table-sort-header.html" with description="Lender" key="lender" %}
    {% if view == "lent+all" %}
    <th>Event</th>
    {% endif %}
    <th>Actions</th>
  </tr></thead>
  <tbody>
  {% for object in object_list %}
  <tr>
    <td>{{object.item.itemType.name}}</td>
    <td>{{object.item.description}}</td>
    <td>{{object.item.barcode}}</td>
    <td>{{object.extension.extension}}</td>
    <td>{{object.extension.name}}</td>
    <td>{{object.lender}}</td>
    {% if view == "lent+all" %}
    <td>{{object.event}}</td>
    {% endif %}
    <td>
      <a href="{% url "inventory.item.return" pk=object.pk %}"><span class="oi oi-home" title="Gotten back" aria-hidden="true"></span></a>
      <a href="{% url "inventory.item.edit" pk=object.item.pk %}"><span class="oi oi-pencil" title="Edit" aria-hidden="true"></span></a>
    </td>
  </tr>
  {% endfor %}
  </tbody>
</table>
{% include "pagination-search-footer.html" %}


{% endblock %}

core/templates/inventory/item/list.html
{% extends "master.html" %}
{% load crispy_forms_tags %}

{% block content %}
{% if request.resolver_match.view_name == "inventory.item.list" %}
    {% include "inventory/item/inventory-nav.html" with view="inventory" %}
{% else %}
    {% include "inventory/item/inventory-nav.html" with view="event_inventory" %}
{% endif %}

<h1>Inventory</h1>
{% if request.user.is_staff %}
<ul class="nav justify-content-end mb-2">
  <li class="nav-item">
    <a class="nav-link" href="{% url "inventory.type.list" %}"><span class="oi oi-folder"></span> Manage inventory types</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url "inventory.dect_suggestions" %}"><span class="oi oi-phone"></span> DECT IPEI assist</a>
  </li>
</ul>
{% endif %}
<ul class="nav justify-content-end mb-2">
  {% if request.user.is_staff %}
  <li class="nav-item">
    <a class="nav-link" href="{% url "inventory.item.new" %}"><span class="oi oi-plus"></span> Add inventory item</a>
  </li>
  {% endif %}
  <li class="nav-item">
    <a class="nav-link" href="{% url "inventory.item.list.csv" %}"><span class="oi oi-data-transfer-download"></span> Download inventory CSV</a>
  </li>
</ul>
<ul class="nav justify-content-end mb-2">
  <li class="nax-item>">
    <a class="nav-link" href="{% url "inventory.box.pack" %}"><i class="fa-solid fa-boxes-packing"></i> Pack box</a>
  </li>
  {% if request.user.is_staff %}
      <li class="nax-item>">
          <a class="nav-link" href="{% url "inventory.box.assign_event" %}"><i class="fa-solid fa-truck-fast"></i> Event item management</a>
      </li>
  {% endif %}
</ul>

<hr/>
{% crispy form form.get_form_helper %}
<hr/>
<div>
{% include "search-form.html" with placeholder="Descriptions, serial numbers, MACs ..." show_decommissioned=True %}
</div>
<p class="text-info">
  {{paginator.count}} items found.
</p>
<table class="table table-striped">
  <thead><tr>
    {% include "table-sort-header.html" with description="Type" key="type" %}
    {% include "table-sort-header.html" with description="Description" key="description" %}
    {% include "table-sort-header.html" with description="Box" key="containedIn" %}
    {% include "table-sort-header.html" with description="Barcode" key="barcode" %}
    <th>Status</th>
    <th>Actions</th>
  </tr></thead>
  <tbody>
  {% for object in object_list %}
  <tr>
    <td>{{object.itemType.name}}</td>
    <td>{{object.description}}</td>
    <td>{% if object.containedIn is not None %}{{object.containedIn}}{% endif %}</td>
    <td>{{object.barcode}}</td>
    <td>
      {% if object.isCurrentlyOnStock %}
      <span class="oi oi-home" title="on stock" aria-hidden="true"></span>
      {% else %}
      <span class="oi oi-globe" title="out there" aria-hidden="true"></span>
      {% endif %}
    </td>
    <td>
      {% if object.isCurrentlyOnStock %}
      <a href="{% url "inventory.item.lend" pk=object.pk %}"><span class="oi oi-transfer" title="Hand out" aria-hidden="true"></span></a>
      {% else %}
      <a href="{% url "inventory.item.return" pk=object.getCurrentLending.pk %}"><span class="oi oi-home" title="Gotten back" aria-hidden="true"></span></a>
      {% endif %}
      <a href="{% url "inventory.item.edit" pk=object.pk %}"><span class="oi oi-pencil" title="Edit" aria-hidden="true"></span></a>
      {% if request.user.is_staff %}
      <a href="{% url "inventory.item.delete" pk=object.pk %}"><span class="oi oi-x" title="Delete" aria-hidden="true"></span></a>
      {% endif %}
    </td>
  </tr>
  {% endfor %}
  </tbody>
</table>
{% include "pagination-search-footer.html" %}

<script>
  $(document).ready(function () {
    var qaMode = localStorage.getItem("qamode");
    if (qaMode != null) {
      $("#id_mode").val(qaMode);
    }
    $("#id_mode").change(function () {
      localStorage.setItem("qamode", $(this).val());
    });
  });
</script>

{% endblock %}

core/templates/inventory/item/return.html
{% extends "master.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h2>Return inventory item</h2>

{% if form.errors %}
<div class="alert alert-danger" role="alert">
    Please correct your inputs!
</div>
{% endif %}
<h4>Item info</h4>
{{ object.item.description }} [{{ object.item.barcode }}] currently lend to {{ object.lender }}
{% if object.extension %}
    <br />
    Linked to {{ object.extension.extension }} ({{ object.extension.name }}).
{% endif %}

<h4 class="mt-2">Return</h4>

{% crispy form form_helper %}

    <script>
        document.addEventListener('DOMContentLoaded', (event) => {
            const box_barcode = document.getElementById('id_box_barcode');
            const box_desc = document.getElementById("box_description");

            function updateBoxInfo() {
                const barcode = box_barcode.value;
                $.getJSON("{% url "inventory.item.barcode_info" %}", {q: barcode}, function (data) {
                    if (data.results.length != 1) { return;}
                    box_desc.textContent = data.results[0].description;
                });
            }

            if (box_barcode.value != "") {
                updateBoxInfo();
            }

            box_barcode.addEventListener('keydown', (e) => {
                if (e.key == 'Enter' || e.key == 'Tab') {
                    updateBoxInfo();
                }
            });
            box_barcode.focus();
        });
    </script>

{% endblock %}